### ISSUE TITLE
Upgrade TensorFlow dependency

### ISSUE THREAD

**Issue by gaul** [TalwalkarLab/paleo#10]
Presently Paleo can only use TensorFlow 0.12.  Running with the latest 1.6.0 generates an error:

```
$ ./paleo.sh profile nets/inception_v3.json 
Network: nets/inception_v3.json
Direction: forward
Traceback (most recent call last):
  File "paleo/profiler.py", line 427, in <module>
    cli()
  File "/home/gaul/.virtualenvs/paleo/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/gaul/.virtualenvs/paleo/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/gaul/.virtualenvs/paleo/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gaul/.virtualenvs/paleo/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gaul/.virtualenvs/paleo/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "paleo/profiler.py", line 414, in profile
    _print_tabular(cu, tf)
  File "paleo/profiler.py", line 343, in _print_tabular
    assert len(cudnn_result) == len(tensorflow_result)
TypeError: object of type 'NoneType' has no len()
```

**Comment by gaul** [comment]
Sorry for the noise, this error is unrelated to TensorFlow version.
